### ISSUE TITLE
Q

### ISSUE THREAD

**Issue by frk1337** [coldcoffeecode/VirusTotalUploader#1]
*Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xfcefurkan/vtl/VirusTotalUploader/vtfilescan.py", line 25, in <module>
    foo = response.json()
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)*``

**Comment by coldcoffeecode** [comment]
I'll take a look - thx

**Comment by coldcoffeecode** [comment]
What OS and version of python3 are you running? I just created a fresh Ubuntu EC2 on AWS and it ran vtfilescan without any errors after installing python3-pip and vt. 

I'm running Python 3.10.6 on Ubuntu 22.04.2 LTS

Also got it to run on my macbook with:
python3 --version
Python 3.11.2

**Comment by frk1337** [comment]
_,met$$$$$gg.          xfcefurkan@cs-13 
    ,g$$$$$$$$$$$$$$$P.       -------------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 
 ,$$P'              `$$$.     Host: Google Compute 
',$$P       ,ggs.     `$$b:   Kernel: 5.15.65+ 
`d$$'     ,$P"'   .    $$$    Uptime: 24 mins 
 $$P      d$'     ,    $$P    Packages: 747 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.1.4 
 $$;      Y$b._   _,d$P'      Terminal: /dev/pts/0 
 Y$$.    `.`"Y$$$$P"'         CPU: AMD EPYC 7B12 ( 
 `$$b      "-.__              Memory: 590MiB / 795 
  `Y$$
   `Y$$.                                           
     `$$b.                                         
       `Y$$b.
          `"Y$b._
              `"""
Python 3.9, I have to try in 3.10?

**Comment by frk1337** [comment]
Code Working but given error large file uploaded 
So what file size Max?

**Comment by coldcoffeecode** [comment]
32MB is the largest file size for the standard API. It is possible to upload files up to 200MB, but this requires permissions by VirtusTotal:
https://developers.virustotal.com/v2.0/reference/file-scan-upload-url

**Comment by frk1337** [comment]
I wish I knew beforehand anyway your code works fine

**Comment by coldcoffeecode** [comment]
I'll add that to the documentation - thanks!

**Comment by coldcoffeecode** [comment]
closing issue
